### PR TITLE
Converted ResultPage from Fragment to Activity + minor changes

### PR DESCRIPTION
**Pull request by joakimljunglin**

### CODE REVIEW

**Comment by joakimljunglin** [comment]
@den027 
Referring to the issue question about the result page:

Your suggestion made sense to me, so I've now reformatted the result page to an activity instead of a fragment, which immediately solved the current errors.

Please review this and get back to me if I should merge it into master.

**Review by ghost — CHANGES_REQUESTED** [review]
It appears fine to me.

I think you should refactor the name so that it is "ResultActivity" rather than "ResultFragment", I assume the ResultModel file can also be deleted.

**Comment by joakimljunglin** [comment]
I've renamed and removed the relevant files now. Should I merge it?

It would also be great if you could connect your activities to the result page. Then I can debug it if need be.

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
I have connected the activities

**Comment by ghost** [comment]
I will merge this to main for now as it appears to work fine, and to get rid of the current error which causes the app not to start. Feel free to create a new PR if you feel something else needs to be changed.

**Pull request merged**
