### PR TITLE
Result page

### PR DESCRIPTION
**Pull request by joakimljunglin**
The result page is found under example tab 6 in the navigation drawer. All the data is hardcoded for now, since it's dependent on the test which is taken.

The functionality (which retrieves the necessary info) is as of now designed to fit Dennis's function (under the reading activity) that redirects to the result page after the test is done.

We should also implement some resources to store category-specific data; like colors and logos/icons which will be used throughout the entire app. I saw that Eva did some kind of resource like this for the icons.

Feedback on design and/or functionality is welcome.

Edit:
Landscape mode needs work.

Edit 2:
Design for landscape mode added, see commits.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
For reference, the display looks like this on my emulator:
Skärmavbild 2020-12-28 kl  15 24 24

I noticed some of the widths and heights are hard coded. This causes issues since it makes the content less flexible to changing screen sizes. I would also personally find it easier to use a different layout type than constraintlayout for this.

I think the button height should be kept to wrap_content as it looks a bit off to me right now.

**Comment by joakimljunglin** [comment]
Thanks for the feedback. I've re-created the design to be responsive. Thanks for the tip on using a different layout type.
Feedback on further changes, or if it still isn't fully responsive, is welcome!

**Review by ghost — COMMENTED** [review]
Skärmavbild 2020-12-30 kl  14 27 58

I'm still having issues with the button (see above). What I would do is remove the styling (text size, bold and the margin), and leave it to default. You can use `style="@style/Widget.MaterialComponents.Button"` to be sure, but I think it may be applied by default. Is there any reason for changing the text size? See this for reference: https://material.io/components/buttons.

By the way, feel free to go outside the sketched design if you feel you can improve on it. I think it's easier to judge the design when it's being implemented than just sketched.

It's possible making the button text size smaller may make it look out of place compared to the big font sizes of the other text items. I'm not sure what would be a satisfying design here. I would probably make all of the fonts smaller, and then try to reduce the empty space by making the banner at the top bigger or something (is it possible to make it more interesting like a gradient or something?)

Maybe this gives some inspiration:
Skärmavbild 2020-12-30 kl  14 48 06

Also, I think the text of the test name may not display as intended on landscape mode:
Skärmavbild 2020-12-30 kl  15 00 39

So, just to be sure. Sorting out the button display (picture 1) is most important. The landscape mode issue on the last picture probably should be sorted out as well. Anything else is up to whether there is time for it. I don't want to request too much as I know everyone is quite busy as it is.

**Comment by joakimljunglin** [comment]
Thanks again for the detailed feedback.
I've made some updates and tested with various devices, hopefully it's more responsive this time around. Please give it another try and see if you can find any other fundamental improvements.

If i find myself with some spare time i will look into improving the design further beyond this.

**Review by ghost — APPROVED** [review]
It looks better for me now. I will approve it with the notion that further improvements are possible if there is time for it. Not sure I mentioned it, but the icon could be made the same as those representing the different activities on the home page, rather than the star.

**Comment by joakimljunglin** [comment]
Great.
I have implemented the switch to the appropriate icon in code, but as of now it still needs some kind of run-time decision on what activity it's showing results for. I'm thinking that this decision (as well as for testname and points) is dependent on what is received from the previous test-page. Then from that received information the icon's source will be set to the correct icon-resource.

Other solutions for doing this is of course welcome.

**Comment by ghost** [comment]
> Great.
> I have implemented the switch to the appropriate icon in code, but as of now it still needs some kind of run-time decision on what activity it's showing results for. I'm thinking that this decision (as well as for testname and points) is dependent on what is received from the previous test-page. Then from that received information the icon's source will be set to the correct icon-resource.
> 
> Other solutions for doing this is of course welcome.

The test pages look like this at the moment: 
`intent.putExtra("correctAnswers", correctAnswers)
  intent.putExtra("totalAnswers", answers.size)
  intent.putExtra("activity", "listening")`

Let me know if you want it formatted differently or some other data to be sent. Everything up to the result page should now be merged to main (hope it runs without any issues), so feel free to merge this one when you can. I can do the necessary changes in the test-activities later if needed (as they now direct back to the home page).

**Comment by joakimljunglin** [comment]
I don't think that should be necessary. I've done some kind of solution to getting what is needed now, but may need to debug it. That will be easy when it's merged to master though, since all the connections are there. I'm not sure if i have missed any details to make it fit in with the rest of the app though, so that might need to be checked.

**Pull request merged**
