### PR TITLE
Select activities fixes

### PR DESCRIPTION
**Pull request by ediuva**
added modifications to deselect difficulty item and link the 3 first activities to their test pages

### CODE REVIEW

**Comment by ghost** [comment]
Skärmavbild 2021-01-05 kl  12 50 06

It doesn't run for me

**Comment by ediuva** [comment]
Well it works fine for me
Maybe you can try to clean and rebuild the project

**Comment by ghost** [comment]
> Well it works fine for me
> Maybe you can try to clean and rebuild the project

Thank you for the advice, it works fine for me now as well.

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
I assume it is fine to merge this to main

**Pull request merged**
